
image: kalashkov/test

services:
  - name: docker:dind

before_script:
  - docker info

stages:
  - test

.setup_test_env:
  before_script:
    - cd lab04/
    - rm report.html

2fa:
  stage: test
  when: always
  extends: .setup_test_env
  services:
    - docker:dind
  script:
    - docker compose up --abort-on-container-exit
    # - docker run --rm -i --name lab04 kalashkovpaul/lab04:latest npm run test
  artifacts:
    paths:
      - test-reports
    expire_in: 1 hour
