export const apiConfig = {
    port: 8004,
    url: "localhost",
    getUser: `/api/user`,
    onEvent: `/api/event`,
    checkRights: `/api/check`,
    saveHero: `/api/save`,
    getSkills: `/api/skills`,
    getSkill: `/api/skill`,
    createSkill: `/api/skill/create`,
    deleteSkill: `/api/skill/delete`,
    saveSkill: `/api/skill/save`,
    getWorks: `/api/works`,
    getWork: `/api/work`,
    createWork: `/api/work/create`,
    deleteWork: `/api/work/delete`,
    saveWork: `/api/work/save`,
}