version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: postgres-sd
    environment:
      POSTGRES_PASSWORD: postgres
      PG_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"